name: Build and Deploy React App

on:
  push:
    branches:
      - main # Altere se sua branch principal for diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Verifique a versão compatível com seu projeto

      - name: Instalar dependências
        run: npm install

      - name: Construir o projeto
        run: npm run build

      - name: Deploy para o GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
